#!/bin/bash
# systemctl --user stop  dharma-wake-daemon 1>/dev/null
# systemctl --user set-environment TOUCHSCREEN="$TOUCHSCREEN" DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY"
# systemctl --user start dharma-wake-daemon

dunst &
# picom --backend glx &
feh --bg-scale ~/.wallpapers/bg1.jpg &
# ( while true; do dmenu_app_list -u && sleep 460; done) &
# xss-lock ~/dharma/lock &
# sleep 2 && setxkbmap -option 'ctrl:nocaps' ; setxkbmap 'us,ru' ',winkeys' 'grp:win_space_toggle' &
# xset r rate 200 50 &
unclutter-xfixes --timeout 0 --ignore-scrolling --jitter 9999 --hide-on-touch --start-hidden --fork &
echo "Xft.dpi: 200" | xrdb -merge
